# 데이터 분석 패키지

* NumPy: 다차원 배열(n-dimensional array)을 다루는 패키지. 머신 러닝에서 중요하게 사용됨
* pandas: 시리즈(Series)와 데이터프레임(DataFrame)을 다루는 패키지. 데이터 분석에서 기본으로 사용하는 패키지
* matplotlib: 데이터 시각화(그래프)
* seaborn: 데이터 시각화

Google Colab에는 데이터 분석과 머신 러닝에 필요한 대부분의 패키지들이 이미 설치되어 있음

In [3]:
import numpy as np
import pandas as pd
import matplotlib
import seaborn as sns

In [4]:
print('Numpy version:', np.__version__)
print('pandas version:', pd.__version__)
print('matplotlib version', matplotlib.__version__)
print('seaborn version:', sns.__version__)

Numpy version: 1.21.6
pandas version: 1.3.5
matplotlib version 3.2.2
seaborn version: 0.11.2


# Python `list` class

* 여러 개의 값들을 저장할 수 있는 데이터 타입
* 인덱스를 기반으로 값들을 저장, 참조
    * indexing: 인덱스로 원하는 위치에 값을 참조, 변경
    * slicing: `[start:end)` 인덱스 범위의 값들로 이루어진 부분집합(리스트)를 잘라냄
* `list + list`: extend. 2개의 리스트를 이어 붙여 하나의 리스트로 만듦
* `list * int, int * list` 리스트의 원소들을 정수만큼 반복해서 복제

In [16]:
list1 = [1,2,3,4,5]
list2 = [10, 20, 30, 40, 50]

In [17]:
# indexing
print(list1[0])
print(list1[-1], list1[4])

1
5 5


In [18]:
# slicing
print(list1[:3])    # list1[0:3]
print(list1[-3:], list1[2:], list1[2:5])

[1, 2, 3]
[3, 4, 5] [3, 4, 5] [3, 4, 5]


In [19]:
print(list1 + list2)    # 아래와 같아 보이지만 각각의 리스트를 변경하진 않고, 합친 결과만 리턴
list1

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]


[1, 2, 3, 4, 5]

In [20]:
list1.extend(list2)   # 위와 같아 보이지만  list1이 변경됨
list1

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [21]:
list2 * 2

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [22]:
2 * list2

[10, 20, 30, 40, 50, 10, 20, 30, 40, 50]

In [23]:
list1 = [1,2,3]
list2 = [4,5,7]

# 같은 인덱스(위치)의 원소들끼리 덧셈
[x + y for x, y in zip(list1,list2)]

[5, 7, 10]

# NumPy

* Numerical Python
* 배열(`ndarray`)을 쉽고 빠르게 연산(`+, -, *, /, ...`)을 할 수 있는 라이브러리
* NumPy 패키지의 함수 또는 메서드들은 대부분 반복문의 기능을 가지고 있음
* `np.ndarray` 클래스: NumPy 패키지의 기본 타입 클래스. n차원 배열(n-dimensional array)
    * `ndarray`는 같은 인덱스(위치)의 원소들끼리(element-wise) 연산을 수행

In [27]:
array1 = np.array([1,2,3])

In [32]:
type(array1)

numpy.ndarray

In [28]:
print(array1)   # print 함수는 __str__ 메서드 이용

[1 2 3]


In [29]:
array1   # expression 출력은 __repr__ 메서드 이용

array([1, 2, 3])

In [30]:
array2 = np.array([10,20,30])

In [31]:
# ndarray의 사칙연산:   element-wise 연산 (같은 인덱스의 원소들끼리 연산)
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)

[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]


## `ndarray` 속성들

In [ ]:
print(array1)  # ndarray
print('ndim:', array1.ndim)  # 차원(dimension): 축(axis)의 개수.
print('size:', array1.size)  # 크기(원소의 개수)
print('shape:', array1.shape)  # 모양(각 차원에서의 원소 개수. 각 축을 따라서 있는 원소의 개수)
print('dtype:', array1.dtype)  # 데이터 타입 - ndarray는 한가지 타입의 값들만 저장.

[1 2 3]
ndim: 1
size: 3
shape: (3,)
dtype: int64



* Python 숫자 타입: 정수(int), 실수(float)
* np 숫자 타입: 
    * 정수(int8, int16, int32, int64, ...)
    * 실수(float16, float32, float64, ...)


## 2차원 `ndarray`

In [ ]:
array_2d = np.array([
    [1, 2, 3, 4], 
    [5, 6, 7, 8], 
    [9, 10, 11, 12]
    ])

In [ ]:
print(array_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print('ndim:', array_2d.ndim)  # 차원
print('size:', array_2d.size)  # 크기
print('shape:', array_2d.shape)  # 모양
print('dtype:', array_2d.dtype)  # 데이터 타입

ndim: 2
size: 12
shape: (3, 4)
dtype: int64


# `ndarray` 객체 생성 함수

`np.array(object, dtype=None, ...)`

* object: 배열과 비슷한 객체들(list, tuple, set, dict, ndarray, ...). ndarry를 생성하기 위한 데이터.


In [ ]:
# 0 이상 10 이하(11 미만)의 짝수들로 이루어진 ndarray
evens = np.array([2 * x for x in range(6)])  # list -> ndarray
print(evens)

[ 0  2  4  6  8 10]


`np.reshape(array, shape)` 함수

`np.ndarray.reshape(shape)` 메서드

In [37]:
arr = np.arange(12)  # [0,12) 범위의 정수들로 이루어진 1차원 배열
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [38]:
arr2 = np.reshape(arr, (3,4))   # (12,) -> (3,4) 모양으로 변환
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
arr.reshape((3,4))  # 메서드 호출

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
np.arange(12).reshape((4,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

`np.random.rand(d0,d1,d2,...)` 함수

* `[0,1)` 범위의 균등분포를 따르는 난수들로 이루어진 ndarray를 만듦
* `d0, d1, d2, ...`: ndarray에서 각 차원의(각 축을 따라서 있는) 원소들의 개수

In [41]:
np.random.rand(5)

array([0.35156597, 0.10309232, 0.47083774, 0.87412736, 0.87877075])

In [42]:
np.random.rand(4,3)

array([[0.8824075 , 0.2705777 , 0.56864905],
       [0.59828781, 0.42946335, 0.71960421],
       [0.04498804, 0.1650672 , 0.48138617],
       [0.85885922, 0.29044722, 0.87497026]])

`np.random.randn(d0, d1, d2,...)` 함수

* 평균이 0이고 표준편차가 1인 표준정규분포(standard narmal distribution)를 따르는 난수들의 배열을 만듦
* d0, d1, d2, ...: ndarray의 각 축을 따라서 있는 원소들의 개수

In [43]:
np.random.randn(5)

array([ 0.58568557, -1.61725677, -1.55292274, -0.75647337, -1.16027502])

In [44]:
np.random.randn(3,4)

array([[ 0.24164336, -0.6723202 ,  1.3771573 ,  2.06715901],
       [-1.02419408,  0.45768428,  1.12542605,  1.07667887],
       [ 1.98216804,  0.38132782, -0.27306202,  0.71759323]])

`np.random.randint(low, high, size, dtype) 함수

* `[low, high)` 범위의 균등분포를 따르는 정수 난수들의 배열 만듦
* `size`: ndarray의 모양(shape). 정수 또는 정수들의 tuple
* dtype: ndarray

# ndarray를 사용한 수학 그래프

# ndarray 인덱스

## indexing, slicing

In [45]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [47]:
# indexing
print(arr[0])  # 배열의 첫 번째 원소
print(arr[-1])  # 배열의 마지막 원소    # ndarray도 list와 마찬가지로 음수 인덱스 사용 가능

0
9


In [48]:
# slicing
print(arr[0:3])  # 배열에서 첫 3개의 원소를 잘라 냄
print(arr[:3])   # 시작 인덱스를 생략하면 0부터 잘라 냄
print(arr[-3:])  # 종료 인덱스를 생략하면 마지막 원소까지 잘라 냄

[0 1 2]
[0 1 2]
[7 8 9]


In [ ]:
# ndarray를 slicing한 결과는 ndarray
print(arr[:1])   # slicing -> ndarray
print(arr[0])    # indexing


## fancy indexing

* 배열과 비슷한 객체(ndarray, list, tuple, set, ...)를 사용해서 원하는 원소들을 참조(indexing)하는 방법
* fancy indexing의 결과는 ndarray

In [49]:
np.random.seed(1)  # 난수 만드는 순서 고정
arr = np.random.randint(100,size=10)  # 100 미만의 정수 난수 10개
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [52]:
arr[[0,2,4,9]]  # ndarray[array-like]

array([37, 72, 75,  1])

## boolean indexing

* 논리값(True/False)들의 배열(리스트, 튜플, ...)을 사용한 fancy indexing
* 배열에서 조건을 만족하는 원소들로 이루어진 부분집합(ndarray)을 만듦

In [53]:
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [ ]:
indices = []

### 2차원 list의 인덱스 사용 방법

In [54]:
list_2d = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
]

In [55]:
list_2d[0]

[1, 2, 3, 4]

In [56]:
list_2d[0][0]

1

# NumPy 통계 함수/메서드

* `np.function(array)` 함수
* `np.ndarray.method()` 메서드

In [57]:
np.random.seed(1)
arr = np.random.randint(100, size=5)

In [58]:
print(arr)

[37 12 72  9 75]


In [59]:
np.sum(arr)  # 함수

205

In [60]:
arr.sum()   # 메서드

205

In [61]:
print('합계:', np.sum(arr), arr.sum())
print('평균:', np.mean(arr), arr.mean())
print('분산:', np.var(arr), arr.var())  # variance
print('표준편차:', np.std(arr), arr.std())   # standard deviation
print('최댓값:', np.max(arr), arr.max())
print('최솟값:', np.min(arr), arr.min())
print('중앙값:', np.median(arr))   # median() 기능은 ndarray의 메서드로 제공되지 않음
# 중앙값: 데이터를 오름차순 정렬했을 때 가운데 있는 값 (짝수개가 있으면 가운데 2개의 평균)

합계: 205 205
평균: 41.0 41.0
분산: 799.6 799.6
표준편차: 28.27719929554552 28.27719929554552
최댓값: 75 75
최솟값: 9 9
중앙값: 37.0


In [62]:
np.sort(arr)  # 배열을 오름차순 정렬한 새로운 배열 리턴. 원본 배열은 변경되지 않음

array([ 9, 12, 37, 72, 75])

In [ ]:
# arr.sort()   # 원본 배열을 정렬해서 변경

In [63]:
print('argmax:', np.argmax(arr), arr.argmax())  # 최대값의 인덱스
print('argmin:', np.argmin(arr), arr.argmin())  # 최소값의 인덱스

argmax: 4 4
argmin: 3 3


## 2차원 배열에서의 통계 함수/메서드

In [64]:
np.random.seed(2)
arr = np.random.randint(100, size=(3,4))
print(arr)

[[40 15 72 22]
 [43 82 75  7]
 [34 49 95 75]]


In [ ]:
np.sum(arr, )